Add khiops_env in conda packages
With 3 new environment variables KHIOPS_PATH, KHIOPS_COCLUSTERING_PATH, KHIOPS_ENV_PATH, the scripts khiops,
khiops_coclustering and khiops-env are generic, we can adapt them to all plateforms. These variables are set
in the 3 scripts by cmake at the configuration step.

The khiops-core packages contains 3 more files: khiops_env, khiops and khiops-coclustering (these 2 lasts
are not mandatory but it facilitates the debugging and tests)

The MODL binary is used to get proc number in khiops_env

On UNIXes we have khiops-env, on windows khiops_env.cmd. Renaming of khiops-env to khiops_env to uniformize names between Windows and UNIXes.

Khiops_env for UNIXes
- Add function get_script_dir funtion in khiops-env.
in conda environment, the PREFIX variable is not always set. In order to set the binaries path, we use this new function.
The khiops binaries are collocated with the khiops-env script (except on fedora-like os)

NSIS
- Add replaceInfile function in NSIS, used to set the KHIOPS_HOME variable during the installation.
- NSIS code simplification

Improve khiops_env for windows
- get KHIOPS_PROC_NUMBER with command line
- add a new variable GUI which is set by cmake or nsis. This variable conditions the setting of the java related variables.
- add KHIOPS_MPI_ERROR, KHIOPS_JAVA_ERROR and KHIOPS_COCLUSTERING_PATH to fit to the UNIXes script
- We use %~dp0 to set KHIOPS_HOME, it is the directory of the script. It is no longer necessary to set KHIOPS_HOME with NSIS (or cmake) or export it.
- check mpi implementation of mpiexec

Improve khiops.cmd
- use %~dp0 to locate khiop_env.cmd (no need for KHIOPS_HOME anymore)
- use KHIOPS_MPI_ERROR and KHIOPS_JAVA_ERROR

install.cmake
- produce khiops_env.cmd
- minor fixes in UNIXes scripts
- Improve KNI package for conda: put the .dll in the bin directory and the .lib in the lib directory (as it is for KNI.zip).
- Call khiops_env -env in action test-khiops-on-iris

conda.yml
- use cmd shell for testing conda package on windows
- force process number to test in parallel

Modify khiops_env.cmd API to be the same on Windows and UNIXes
- When using the '--env' flag, variables will only be displayed without changing the environment. It is useful in debugging.

Improve the action test-khiops-install
- test khiops-env playing with KHIOPS_PROC_NUMBER

diff --git a/packaging/linux/common/khiops_coclustering b/packaging/linux/common/khiops_coclustering
--- a/packaging/linux/common/khiops_coclustering
+++ b/packaging/linux/common/khiops_coclustering
@@ -1,38 +1,49 @@
 #!/bin/bash
 
 # Run Khiops tool
-# see the khiops-env script for full documentation on the environment variables used by Khiops
-
-
+# see the khiops_env script for full documentation on the environment variables used by Khiops
 
 error() {
-    logger "$*" --tag khiops --stderr
-    if [ -n "$DISPLAY" ] 
+    if [ -f /dev/log ]; then
+        logger "$*" --tag khiops --stderr
+    else
+        echo "$*" >&2
+    fi
+    if [ -n "$DISPLAY" ]
     then
         notify-send "Khiops" "$*" -i /usr/share/pixmaps/khiops.png -u normal;
     fi
-    exit 1; 
+    exit 1;
 }
-
 
 warning() {
-    logger "$*" --tag khiops --stderr
-    if [ -n "$DISPLAY" ] 
+    if [ -f /dev/log ]; then
+        logger "$*" --tag khiops --stderr
+    else
+        echo "$*" >&2
+    fi
+    if [ -n "$DISPLAY" ]
     then
         notify-send "Khiops" "$*" -i /usr/share/pixmaps/khiops.png -u normal;
     fi
 }
 
-if [[ ! -f /usr/bin/khiops-env ]]; then
-    error "/usr/bin/khiops-env is missing"
+get_script_dir(){
+    SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+    echo "$SCRIPT_DIR/"
+}
+
+if [[ ! -f "$(get_script_dir)"/khiops_env ]]; then
+    echo "$(get_script_dir)/khiops_env is missing"
+    exit 1
 fi
 
-# initialize Khiops environment
-source /usr/bin/khiops-env ""
+# Initialize Khiops env variables
+source $(get_script_dir)/khiops_env ""
 
 # Test if batch mode from parameters
 KHIOPS_BATCH_MODE=false
-for ((i=1;i<=$#;i++)); 
+for ((i=1;i<=$#;i++));
 do
     if [ ${!i} = "-b" ] || [ ${!i} = "-h" ] || [ ${!i} = "-s" ] || [ ${!i} = "-v" ]; then
         KHIOPS_BATCH_MODE=true
@@ -40,16 +51,15 @@ do
     fi
 done;
 
-
-if [[ ! -e $KHIOPS_PATH/MODL_Coclustering ]]; then
-    error "Binary not found ($KHIOPS_PATH/MODL_Coclustering)"
+if [[ ! -e $KHIOPS_COCLUSTERING_PATH ]]; then
+    error "Binary not found ($KHIOPS_COCLUSTERING_PATH)"
 fi
 
-# Test multiple possible errors with the java GUI 
+# Test multiple possible errors with the java GUI
 if [  "$KHIOPS_BATCH_MODE" = false ]; then
     if [ -z "$DISPLAY" ]; then
         error "GUI is not available, please use the '-b' flag"
-    elif [ -z "$KHIOPS_JAVA_PATH" ]; then
+        elif [ -z "$KHIOPS_JAVA_PATH" ]; then
         if [ -z "$KHIOPS_JAVA_ERROR" ]; then
             error "The khiops GUI is not configured properly. Please (re)install the 'khiops' package."
         else
@@ -65,10 +75,10 @@ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KHIOPS_JAVA_PATH
 if [[  $# -eq 0  ]]; then
     # run without parameters
     # run and save scenario and log files in directory KHIOPS_LAST_RUN_DIR
-    MODL_Coclustering -o "${KHIOPS_LAST_RUN_DIR}"/scenario._kh -e "${KHIOPS_LAST_RUN_DIR}"/log.txt
+    $KHIOPS_COCLUSTERING_PATH -o "${KHIOPS_LAST_RUN_DIR}"/scenario._kh -e "${KHIOPS_LAST_RUN_DIR}"/log.txt
 else
     # run with parameters
-    MODL_Coclustering "$@"
+    $KHIOPS_COCLUSTERING_PATH "$@"
 fi
 
 exit $?
