Add function get_script_dir funtion in khiops-env
In conda environment, the PREFIX variable is not always set. In order to set the binaries path, we use this new function.
The khiops binaries are collocated with the khiops-env script (except on fedora-like os)

diff --git a/packaging/linux/common/khiops_coclustering b/packaging/linux/common/khiops_coclustering
--- a/packaging/linux/common/khiops_coclustering
+++ b/packaging/linux/common/khiops_coclustering
@@ -3,8 +3,6 @@
 # Run Khiops tool
 # see the khiops-env script for full documentation on the environment variables used by Khiops
 
-
-
 error() {
     if [ -f /dev/log ]; then
         logger "$*" --tag khiops --stderr
@@ -16,7 +14,6 @@ error() {
     exit 1;
 }
 
-
 warning() {
     if [ -f /dev/log ]; then
         logger "$*" --tag khiops --stderr
@@ -27,12 +24,18 @@ warning() {
     fi
 }
 
-if [[ ! -f @KHIOPS_ENV_PATH@/khiops-env ]]; then
-    error "@KHIOPS_ENV_PATH@/khiops-env is missing"
+get_script_dir(){
+    SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+    echo "$SCRIPT_DIR/"
+}
+
+if [[ ! -f "$(get_script_dir)"/khiops-env ]]; then
+    echo "$(get_script_dir)/khiops-env is missing"
+    exit 1
 fi
 
-# initialize Khiops environment
-source @KHIOPS_ENV_PATH@/khiops-env
+# Initialize Khiops env variables
+source $(get_script_dir)/khiops-env ""
 
 # Test if batch mode from parameters
 KHIOPS_BATCH_MODE=false
@@ -44,9 +47,8 @@ do
     fi
 done;
 
-
-if [[ ! -e $KHIOPS_PATH/MODL ]]; then
-    error "Binary not found ($KHIOPS_PATH/MODL)"
+if [[ ! -e $KHIOPS_COCLUSTERING_PATH/MODL_Coclustering ]]; then
+    error "Binary not found ($KHIOPS_COCLUSTERING_PATH/MODL_Coclustering)"
 fi
 
 # Test multiple possible errors with the java GUI
@@ -62,10 +64,6 @@ if [  "$KHIOPS_BATCH_MODE" = false ]; then
     fi
 fi
 
-# Display error with mpi configuration
-if [ -n "$KHIOPS_MPI_ERROR" ]; then
-    warning "$KHIOPS_MPI_ERROR"
-fi
 
 export CLASSPATH=$CLASSPATH:$KHIOPS_CLASSPATH
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KHIOPS_JAVA_PATH
@@ -73,10 +71,10 @@ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KHIOPS_JAVA_PATH
 if [[  $# -eq 0  ]]; then
     # run without parameters
     # run and save scenario and log files in directory KHIOPS_LAST_RUN_DIR
-    $KHIOPS_MPI_COMMAND $KHIOPS_PATH -o "${KHIOPS_LAST_RUN_DIR}"/scenario._kh -e "${KHIOPS_LAST_RUN_DIR}"/log.txt
+    $KHIOPS_COCLUSTERING_PATH -o "${KHIOPS_LAST_RUN_DIR}"/scenario._kh -e "${KHIOPS_LAST_RUN_DIR}"/log.txt
 else
     # run with parameters
-    $KHIOPS_MPI_COMMAND $KHIOPS_PATH "$@"
+    $KHIOPS_COCLUSTERING_PATH "$@"
 fi
 
 exit $?
