Add khiops-env in conda package (Linux and macOS)
With 3 new environment variables KHIOPS_PATH, KHIOPS_COCLUSTERING_PATH, KHIOPS_ENV_PATH, the scripts khiops,
khiops_coclustering and khiops-env are generic, we can adapt them to all plateforms. These variables are set
in the 3 scripts by cmake at the configuration step.

The khiops-core packages contains 3 more files: khiops-env, khiops and khiops-coclustering (these 2 lasts
are not mandatory but it facilitates the debugging and tests)

diff --git a/packaging/linux/common/khiops.in b/packaging/linux/common/khiops.in
--- a/packaging/linux/common/khiops.in
+++ b/packaging/linux/common/khiops.in
@@ -13,7 +13,7 @@ error() {
     then
         notify-send "Khiops" "$*" -i /usr/share/pixmaps/khiops.png -u normal;
     fi
-    exit 1; 
+    exit 1;
 }
 
 
@@ -27,19 +27,19 @@ warning() {
     fi
 }
 
-if [[ ! -f /usr/bin/khiops-env ]]; then
-    error "/usr/bin/khiops-env is missing"
+if [[ ! -f @KHIOPS_ENV_PATH@/khiops-env ]]; then
+    error "@KHIOPS_ENV_PATH@/khiops-env is missing"
 fi
 
 # initialize Khiops environment
-source /usr/bin/khiops-env
+source @KHIOPS_ENV_PATH@/khiops-env
 
 # Test if batch mode from parameters
 KHIOPS_BATCH_MODE=false
-for ((i=1;i<=$#;i++)); 
+for ((i=1;i<=$#;i++));
 do
     if [ ${!i} = "-b" ] || [ ${!i} = "-h" ] || [ ${!i} = "-s" ] || [ ${!i} = "-v" ]; then
-	    KHIOPS_BATCH_MODE=true
+        KHIOPS_BATCH_MODE=true
         break
     fi
 done;
@@ -49,11 +49,11 @@ if [[ ! -e $KHIOPS_PATH/MODL ]]; then
     error "Binary not found ($KHIOPS_PATH/MODL)"
 fi
 
-# Test multiple possible errors with the java GUI 
+# Test multiple possible errors with the java GUI
 if [  "$KHIOPS_BATCH_MODE" = false ]; then
     if [ -z "$DISPLAY" ]; then
         error "GUI is not available, please use the '-b' flag"
-    elif [ -z "$KHIOPS_JAVA_PATH" ]; then
+        elif [ -z "$KHIOPS_JAVA_PATH" ]; then
         if [ -z "$KHIOPS_JAVA_ERROR" ]; then
             error "The khiops GUI is not configured properly. Please (re)install the 'khiops' package."
         else
@@ -73,10 +73,10 @@ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KHIOPS_JAVA_PATH
 if [[  $# -eq 0  ]]; then
     # run without parameters
     # run and save scenario and log files in directory KHIOPS_LAST_RUN_DIR
-    $KHIOPS_MPI_COMMAND MODL -o "${KHIOPS_LAST_RUN_DIR}"/scenario._kh -e "${KHIOPS_LAST_RUN_DIR}"/log.txt
+    $KHIOPS_MPI_COMMAND $KHIOPS_PATH -o "${KHIOPS_LAST_RUN_DIR}"/scenario._kh -e "${KHIOPS_LAST_RUN_DIR}"/log.txt
 else
     # run with parameters
-    $KHIOPS_MPI_COMMAND MODL "$@"
+    $KHIOPS_MPI_COMMAND $KHIOPS_PATH "$@"
 fi
 
 exit $?
