Improve khiops_env (cluster ready and more)
Add KHIOPS_MPI_HOST_FILE to khiops_env
- Allows to specify a hostfile to mpiexec
- if this variable is defined, khiops_env will export environment variables required by khiops to run correctly to MPI processes.
These variables relate to GCS/S3 credentials and to khiops itself (KHIOPS_* and Khiops*)
khiops_env is built on cmake configure: the variable export is done only for openmpi and the hostfile keyword is different for openmpi and mpich

Remove process affinity for MS-MPI
- As discussed in #350, the affinity slows down khiops.
- remove the prioryty (below normal) too

Improve UNIXes khiops_env
- java configuration and modules loading are not in khiops_env on conda environment
- To improve the install.cmake readability, 3 files are added to fill variables:
	- export_env_variables.sh
	- java_settings.sh
	- use_environment_module.sh

fix GUI error message in khiops and khiops coclustering
- The message saying to install "khiops" on conda environment is wrong.
- when a non-existing option is passed, e.g. khiops --foo, the GUI message is displayed

fix message in help about KHIOPS_API_MODE: false <=> true

KHIOPS_API_MODE message

diff --git a/packaging/linux/common/khiops b/packaging/linux/common/khiops
--- a/packaging/linux/common/khiops
+++ b/packaging/linux/common/khiops
@@ -9,11 +9,11 @@ error() {
     else
         echo "$*" >&2
     fi
-    if [ -n "$DISPLAY" ]
-    then
-        notify-send "Khiops" "$*" -i /usr/share/pixmaps/khiops.png -u normal;
+    if [ -n "$DISPLAY" ] && command -v notify-send >/dev/null 2>&1; then
+        notify-send "Khiops" "$*" -i /usr/share/pixmaps/khiops.png -u normal
     fi
-    exit 1;
+    unset _IS_CONDA
+    exit 1
 }
 
 warning() {
@@ -22,14 +22,13 @@ warning() {
     else
         echo "$*" >&2
     fi
-    if [ -n "$DISPLAY" ]
-    then
-        notify-send "Khiops" "$*" -i /usr/share/pixmaps/khiops.png -u normal;
+    if [ -n "$DISPLAY" ]; then
+        notify-send "Khiops" "$*" -i /usr/share/pixmaps/khiops.png -u normal
     fi
 }
 
-get_script_dir(){
-    SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+get_script_dir() {
+    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
     echo "$SCRIPT_DIR/"
 }
 
@@ -43,29 +42,15 @@ source $(get_script_dir)/khiops_env ""
 
 # Test if batch mode from parameters
 KHIOPS_BATCH_MODE=false
-for ((i=1;i<=$#;i++));
-do
+for ((i = 1; i <= $#; i++)); do
     if [ ${!i} = "-b" ] || [ ${!i} = "-h" ] || [ ${!i} = "-s" ] || [ ${!i} = "-v" ]; then
         KHIOPS_BATCH_MODE=true
         break
     fi
-done;
+done
 
 if [[ ! -e $KHIOPS_PATH ]]; then
     error "Binary not found ($KHIOPS_PATH)"
-fi
-
-# Test multiple possible errors with the java GUI
-if [  "$KHIOPS_BATCH_MODE" = false ]; then
-    if [ -z "$DISPLAY" ]; then
-        error "GUI is not available, please use the '-b' flag"
-        elif [ -z "$KHIOPS_JAVA_PATH" ]; then
-        if [ -z "$KHIOPS_JAVA_ERROR" ]; then
-            error "The khiops GUI is not configured properly. Please (re)install the 'khiops' package."
-        else
-            error "$KHIOPS_JAVA_ERROR"
-        fi
-    fi
 fi
 
 # Display error with mpi configuration
@@ -76,13 +61,35 @@ fi
 export CLASSPATH=$CLASSPATH:$KHIOPS_CLASSPATH
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$KHIOPS_JAVA_PATH
 
-if [[  $# -eq 0  ]]; then
-    # run without parameters
-    # run and save scenario and log files in directory KHIOPS_LAST_RUN_DIR
-    $KHIOPS_MPI_COMMAND $KHIOPS_PATH -o "${KHIOPS_LAST_RUN_DIR}"/scenario._kh -e "${KHIOPS_LAST_RUN_DIR}"/log.txt
+launch_khiops() {
+    if [[ $# -eq 0 ]]; then
+        # run without parameters
+        # run and save scenario and log files in directory KHIOPS_LAST_RUN_DIR
+        $KHIOPS_MPI_COMMAND "$KHIOPS_PATH" -o "${KHIOPS_LAST_RUN_DIR}"/scenario._kh -e "${KHIOPS_LAST_RUN_DIR}"/log.txt
+    else
+        # run with parameters
+        $KHIOPS_MPI_COMMAND "$KHIOPS_PATH" "$@"
+    fi
+}
+
+# Launck Khiops
+if [ "$KHIOPS_BATCH_MODE" = true ]; then
+    launch_khiops "$@"
 else
-    # run with parameters
-    $KHIOPS_MPI_COMMAND $KHIOPS_PATH "$@"
+    if [ "$_IS_CONDA" = true ] || [ -z "$DISPLAY" ]; then
+        error "GUI is not available, please use the '-b' flag"
+    else
+        if [ -z "$KHIOPS_JAVA_PATH" ]; then
+            if [ -z "$KHIOPS_JAVA_ERROR" ]; then
+                error "GUI is not available, please either use the '-b' flag, or install the 'khiops' native package for your host operating system."
+            else
+                error "$KHIOPS_JAVA_ERROR"
+            fi
+        else
+            launch_khiops "$@"
+        fi
+    fi
 fi
 
+unset _IS_CONDA
 exit $?
