Fix the temporary directory check
Use GetTmpDir instead of GetUserTmpDir(). The last one could return empty when the temp dir is not initialized by the user (in the GUI).
Add tests in CI to capture this error

diff --git a/.github/actions/test-khiops-install/action.yml b/.github/actions/test-khiops-install/action.yml
--- a/.github/actions/test-khiops-install/action.yml
+++ b/.github/actions/test-khiops-install/action.yml
@@ -152,12 +152,17 @@ runs:
           echo "::error::This action expects CONDA_ENV_BIN_DIR to be defined"
           false
         fi
-        $KHIOPS_ENV_DIR/khiops -s
-        $KHIOPS_ENV_DIR/khiops -v &> output
-        LINE_NUMBER=$(wc -l < output)
-        if [ $LINE_NUMBER -gt 1 ] ;
+        $KHIOPS_ENV_DIR/khiops -s | tee output_s
+        if [ grep -q Error output_s ];
         then 
-          echo "::error::Unexpected output in khiops scripts"
+          echo "::error::Unexpected output in khiops -s"
+          false
+        fi
+        $KHIOPS_ENV_DIR/khiops -v | tee output_v
+        LINE_NUMBER=$(wc -l < output_v)
+        if [ $LINE_NUMBER -gt 1 ];
+        then 
+          echo "::error::Unexpected output in khiops -v"
           false
         fi
     - name: Check Khiops output [Windows]
@@ -167,6 +172,11 @@ runs:
         KHIOPS_PROC_NUMBER: 4
       run: |
         khiops -s
+        khiops -s 2>&1 | findstr /i "Error" >nul
+        if %ERRORLEVEL% equ 0 (
+          echo "::error::Unexpected output in khiops -s"
+          exit 1
+        ) 
         for /f %%i in (' khiops -v ^| find /c /v "" ') do set "LINE_NUMBER=%%i"
         if not "%LINE_NUMBER%" == "1" (
           echo "::error::Unexpected output in khiops scripts"
@@ -194,12 +204,17 @@ runs:
           echo "::error::This action expects CONDA_ENV_BIN_DIR to be defined"
           false
         fi
-        $KHIOPS_ENV_DIR/khiops_coclustering -s
-        $KHIOPS_ENV_DIR/khiops_coclustering -v &> output
-        LINE_NUMBER=$(wc -l < output)
-        if [ $LINE_NUMBER -gt 1 ] ;
+        $KHIOPS_ENV_DIR/khiops_coclustering -s | tee output_s
+        if [ grep -q Error output_s ];
         then 
-          echo "::error::Unexpected output in khiops_coclustering scripts"
+          echo "::error::Unexpected output in khiops_coclustering -s"
+          false
+        fi
+        $KHIOPS_ENV_DIR/khiops_coclustering -v | tee output
+        LINE_NUMBER=$(wc -l < output)
+        if [ $LINE_NUMBER -gt 1 ];
+        then 
+          echo "::error::Unexpected output in khiops_coclustering -v"
           false
         fi
     - name: Check Khiops coclustering output [Windows]
@@ -209,9 +224,14 @@ runs:
         KHIOPS_PROC_NUMBER: 4
       run: |
         khiops_coclustering -s
+        khiops_coclustering -s 2>&1 | findstr /i "Error" >nul
+        if %ERRORLEVEL% equ 0 (
+          echo "::error::Unexpected output in khiops_coclustering -s"
+          exit 1
+        ) 
         for /f %%i in (' khiops_coclustering -v ^| find /c /v "" ') do set "LINE_NUMBER=%%i"
         if not "%LINE_NUMBER%" == "1" (
-          echo "::error::Unexpected output in khiops_coclustering scripts"
+          echo "::error::Unexpected output in khiops_coclustering -v"
           exit 1
         )
     - name: Check process number [UNIXes]
