183 transform the basetest binary into unit tests (#194)
* Add unit tests for base library

Improve the file comparison to be resilient with the '\' char when it is not a path separator
Export all methods implements in the basetest binary to the base library (except the UI tests)
Add unit tests for all methods run in basetest binary (except the UI)
Add reference files for the new tests

* Improve results comparison for unit tests

The SYS token could be placed in the middle of the line. The part of the lines after this token will not be tested

Finalisation de TestServices:
- nettoyage des fins de ligne
- utilisation d'un buffer de grande taille pour pouvoir stocker un path

* Fix unit test problems in FileService and SystemResource

* Initialize Learning unit tests

Mise en place des test unitaires pour Learning
- une famille de test par librairie
- initialise avec deux tests pour KWData et deux tests pour KWDataPreparation
- Le test de KWProbabilityTable est commenté car il lèv eune assertion
- on peut maintenant integrer les tests unitaires un a un, librairie par librairie

* provide results to download on failure

Search assert check, require in results file and echo if it appears

* mv unit tests directories to test/UnitTests

* add TESTING=OFF when building Khiops in CI/CD

---------

Co-authored-by: Marc Boullé <marc.boulle@orange.com>

diff --git a/.github/workflows/run-unit-tests.yml b/.github/workflows/run-unit-tests.yml
--- a/.github/workflows/run-unit-tests.yml
+++ b/.github/workflows/run-unit-tests.yml
@@ -12,8 +12,8 @@ on:
       - src/**.inc
       - src/**.lex
       - src/**.yac
-      - test/**.h
-      - test/**.cpp
+      - test/UnitTests/**.h
+      - test/UnitTests/**.cpp
 # Cancel any ongoing run of this workflow on the same PR or ref
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
@@ -74,6 +74,31 @@ jobs:
         run: |
           build/${{ matrix.build-setup.cmake-preset }}/bin/KNITest \
             --gtest_output="xml:reports/report-kni.xml"
+      - name: Check assertions
+        if: success() || failure()
+        run: |
+          if (grep -q -E -r "Assert failed in file|Require failed in file|Ensure failed in file|Check failed in file" \
+            test/UnitTests/KNItestresults/ \
+            test/UnitTests/Norm/results/ \
+            test/UnitTests/Learning/results/ \
+            test/UnitTests/Norm/results/ \
+            test/UnitTests/Parallel/results/ \
+            test/UnitTests/Parallel-mpi/results/); then
+            echo "::error::At least one test binary has failed with an assertion (assert, check, require, ensure..). Check result files available for download as artifacts."
+          fi
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: unit-tests-results-${{ matrix.build-setup.os }}
+          retention-days: 7
+          path: |-
+            test/UnitTests/KNItest/results/
+            test/UnitTests/Norm/results/
+            test/UnitTests/Learning/results/
+            test/UnitTests/Norm/results/
+            test/UnitTests/Parallel/results/
+            test/UnitTests/Parallel-mpi/results/
       - name: Create Unit Test Reports Dashboards
         uses: phoenix-actions/test-reporting@v12
         if: success() || failure()
